# Phase 3

 1. 📘 What is NumPy?

NumPy (Numerical Python) is a high-performance library for:

Array computing (faster than lists)

Mathematical operations

Linear algebra, statistics, signal processing

🧠 NumPy’s arrays (ndarrays) are faster and more memory-efficient than Python lists.

In [3]:
# syntax
import numpy as np
np.array([1,2,3])



array([1, 2, 3])

In [6]:
import numpy as np

# 1D Array
a = np.array([1, 2, 3])
print(a)

# 2D Array
b = np.array([[1, 2], [3, 4]])
print(b)

# Create array of zeros, ones
c=np.zeros((2, 3))# 2x3 matrix of zeros
print(c)
d=np.ones((3,))         # 1D array of ones
print(d)
# Create range
e=np.arange(1, 10, 2)   # [1 3 5 7 9]
print(e)
# Create linearly spaced values
f=np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1.]
print(f)


[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


In [7]:
# Array Attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)       # Dimensions (2)
print(arr.shape)      # (2, 3)
print(arr.size)       # Total elements (6)
print(arr.dtype)      # Data type (int64)


2
(2, 3)
6
int32


In [8]:
# Reshape & Indexing
a = np.arange(1, 7).reshape((2, 3))
print(a)

# Access elements
print(a[0, 2])        # Row 0, Col 2 → 3

# Slicing
print(a[:, 1])        # All rows, column 1
print(a[1, :])        # Row 1, all columns


[[1 2 3]
 [4 5 6]]
3
[2 5]
[4 5 6]


In [11]:
# Useful NumPy Functions
arr = np.array([[1, 2], [3, 4]])

print(np.sum(arr))          # Sum of all elements
print(np.mean(arr))          # Mean
print(np.max(arr))           # Max
print(np.min(arr))           # Min
print(np.std(arr))           # Standard deviation
print(np.transpose(arr))     # Flip rows/columns


10
2.5
4
1
1.118033988749895
[[1 3]
 [2 4]]


````
Use np.array() instead of Python lists for math	
Prefer np.arange() for fast looping	
Chain operations: np.mean(arr.reshape(2, 3))	
Use axis=0 (column-wise), axis=1 (row-wise)

In [33]:
# p1 Create a 3x3 matrix of numbers from 1 to 9.
a=np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# p2 Square each element in the matrix
squared_a = np.square(a)
print(squared_a )
a=a**2
print(a)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [36]:
# p3 Create an array of 10 values equally spaced between 0 and 5.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [42]:
#Create a 2D array and calculate: Sum of rows,Mean of columns,Standard deviation of entire array
a=np.arange(1,10).reshape((3,3))
sum_of_rows=np.sum(a,axis=1)
print(sum_of_rows)
mean_of_rows=np.mean(a,axis=0)
print(mean_of_rows)
print(np.std(a))

[ 6 15 24]
[4. 5. 6.]
2.581988897471611


| Topic        | Key Function                                      |
| ------------ | ------------------------------------------------- |
| Create array | `np.array`, `np.arange`, `np.zeros`, `np.ones`    |
| Stats        | `np.sum`, `np.mean`, `np.std`, `np.max`, `np.min` |
| Shape/Index  | `reshape`, `shape`, `ndim`, `size`, slicing       |
| Math ops     | `+`, `-`, `*`, `/`, `np.sqrt`, `**`,np.square     |
